"""
Human Approval System for Silver Tier AI Assistant
Manages sensitive actions requiring human oversight
"""

import os
import json
import time
from datetime import datetime, timedelta
from enum import Enum
from queue import Queue
import threading

class ApprovalStatus(Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXPIRED = "expired"

class ApprovalType(Enum):
    FINANCIAL = "financial"
    CONTRACT = "contract"
    PERSONNEL = "personnel"
    CONFIDENTIAL = "confidential"
    CUSTOMER = "customer"
    GENERAL = "general"

class HumanApprovalSystem:
    def __init__(self, vault_path="silver_vault"):
        self.vault_path = vault_path
        self.pending_approvals_path = os.path.join(vault_path, "Pending_Approval")
        os.makedirs(self.pending_approvals_path, exist_ok=True)
        
        self.active_approvals = {}  # action_id -> approval_data
        self.approval_queue = Queue()
        self.approvers = []  # List of authorized approvers
        self.setup_default_approvers()
        
    def setup_default_approvers(self):
        """Setup default approvers for the system"""
        self.approvers = [
            {
                "id": "mgr_001",
                "name": "Manager",
                "email": "manager@company.com",
                "level": "department",
                "permissions": ["financial", "contract", "personnel", "confidential"]
            },
            {
                "id": "exec_001", 
                "name": "Executive",
                "email": "executive@company.com",
                "level": "executive",
                "permissions": ["financial", "contract", "personnel", "confidential", "customer"]
            }
        ]
    
    def submit_for_approval(self, action_data, action_type=ApprovalType.GENERAL, approver_required=None):
        """Submit an action for human approval"""
        action_id = f"approval_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{len(self.active_approvals)}"
        
        approval_record = {
            "action_id": action_id,
            "action_type": action_type.value,
            "action_data": action_data,
            "submit_time": datetime.now().isoformat(),
            "status": ApprovalStatus.PENDING.value,
            "expires_at": (datetime.now() + timedelta(hours=24)).isoformat(),  # Expires in 24 hours
            "submitted_by": "AI_Assistant",
            "approver_required": approver_required,
            "justification": action_data.get("justification", "Auto-generated by AI"),
            "risk_level": action_data.get("risk_level", "medium")
        }
        
        # Save to pending approvals folder
        self.save_approval_record(action_id, approval_record)
        
        # Add to active approvals
        self.active_approvals[action_id] = approval_record
        
        # Add to queue
        self.approval_queue.put(action_id)
        
        print(f"Action submitted for approval: {action_id} ({action_type.value})")
        
        # Notify approvers
        self.notify_approvers(approval_record)
        
        return action_id
    
    def save_approval_record(self, action_id, approval_record):
        """Save approval record to the Pending_Approval folder"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        filename = f"APPROVAL_{action_id}_{timestamp}.md"
        filepath = os.path.join(self.pending_approvals_path, filename)
        
        content = f"""# Approval Request: {approval_record['action_type'].title()}

## Action ID
{approval_record['action_id']}

## Type
{approval_record['action_type']}

## Submitted At
{approval_record['submit_time']}

## Expiry Time
{approval_record['expires_at']}

## Submitted By
{approval_record['submitted_by']}

## Justification
{approval_record['justification']}

## Risk Level
{approval_record['risk_level']}

## Action Data
```json
{json.dumps(approval_record['action_data'], indent=2, default=str)}
```

## Status
**Current Status:** {approval_record['status']}

## Approval History
- Status: {approval_record['status']}
- Time: {approval_record['submit_time']}
- Reason: Awaiting review

## Required Action
Please review the above request and respond with your decision.
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"Approval record saved: {filename}")
    
    def notify_approvers(self, approval_record):
        """Notify approvers about pending approval"""
        print(f"NOTIFICATION: Action {approval_record['action_id']} requires approval")
        print(f"  Type: {approval_record['action_type']}")
        print(f"  Justification: {approval_record['justification'][:100]}...")
        
        # In a real system, this would send an email or other notification
        # For now, we'll just print the notification
    
    def process_approval_decision(self, action_id, decision, approver_id, reason=""):
        """Process an approval decision"""
        if action_id not in self.active_approvals:
            print(f"Error: Action ID {action_id} not found in active approvals")
            return False
        
        approval_record = self.active_approvals[action_id]
        
        # Update status based on decision
        if decision.lower() == 'approve':
            approval_record['status'] = ApprovalStatus.APPROVED.value
        elif decision.lower() == 'reject':
            approval_record['status'] = ApprovalStatus.REJECTED.value
        else:
            print(f"Invalid decision: {decision}")
            return False
        
        # Add approval history
        approval_record['approval_history'] = approval_record.get('approval_history', [])
        approval_record['approval_history'].append({
            'decision': decision.lower(),
            'approver_id': approver_id,
            'reason': reason,
            'timestamp': datetime.now().isoformat()
        })
        
        # Update the approval record file
        self.update_approval_file(action_id, approval_record)
        
        # Remove from active approvals if approved/rejected
        if decision.lower() in ['approve', 'reject']:
            del self.active_approvals[action_id]
        
        print(f"Approval decision processed: {action_id} - {decision.upper()}")
        return True
    
    def update_approval_file(self, action_id, approval_record):
        """Update the approval file with the latest status"""
        # Find the corresponding file
        for filename in os.listdir(self.pending_approvals_path):
            if action_id in filename and filename.endswith('.md'):
                filepath = os.path.join(self.pending_approvals_path, filename)
                
                with open(filepath, 'r', encoding='utf-8') as f:
                    content = f.read()
                
                # Update status
                content = content.replace("**Current Status:** pending", f"**Current Status:** {approval_record['status']}")
                
                # Add approval history
                history_entry = f"\n- Status: {approval_record['status']}\n- Approver: {approval_record['approval_history'][-1]['approver_id']}\n- Time: {approval_record['approval_history'][-1]['timestamp']}\n- Reason: {approval_record['approval_history'][-1]['reason']}"
                
                # Find approval history section and append
                history_start = content.find("## Approval History")
                if history_start != -1:
                    content = content[:history_start] + f"## Approval History{history_entry}\n\n## Required Action" + content[content.find("## Required Action"):]
                
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
                
                break
    
    def check_expired_approvals(self):
        """Check for and handle expired approvals"""
        current_time = datetime.now()
        expired = []
        
        for action_id, record in self.active_approvals.items():
            expiry_time = datetime.fromisoformat(record['expires_at'])
            if current_time > expiry_time:
                record['status'] = ApprovalStatus.EXPIRED.value
                self.update_approval_file(action_id, record)
                expired.append(action_id)
        
        # Remove expired approvals from active list
        for action_id in expired:
            del self.active_approvals[action_id]
            print(f"Approval expired: {action_id}")
        
        return expired
    
    def get_pending_approvals(self):
        """Get list of all pending approvals"""
        return [
            {
                "action_id": action_id,
                "action_type": record["action_type"],
                "submit_time": record["submit_time"],
                "risk_level": record["risk_level"],
                "justification": record["justification"]
            }
            for action_id, record in self.active_approvals.items()
            if record["status"] == "pending"
        ]
    
    def auto_approve_low_risk(self, threshold="low"):
        """Auto-approve low-risk actions based on risk level"""
        auto_approved = []
        
        for action_id, record in list(self.active_approvals.items()):
            if record["status"] == "pending" and record["risk_level"] == threshold:
                # Auto-approve
                self.process_approval_decision(action_id, "approve", "auto_system", "Auto-approved low-risk action")
                auto_approved.append(action_id)
        
        return auto_approved
    
    def run_approval_cycle(self):
        """Run a cycle of approval processing"""
        print("Running approval system cycle...")
        
        # Check for expired approvals
        expired = self.check_expired_approvals()
        
        # Auto-approve low-risk actions
        auto_approved = self.auto_approve_low_risk("low")
        
        print(f"Approval cycle completed:")
        print(f"  - Expired: {len(expired)}")
        print(f"  - Auto-approved: {len(auto_approved)}")
        print(f"  - Still pending: {len(self.active_approvals)}")

def main():
    print("Initializing Human Approval System...")
    
    # Initialize the approval system
    approval_system = HumanApprovalSystem()
    
    # Test with a sample action
    sample_action = {
        "type": "email_response",
        "subject": "Budget Approval Request",
        "content": "Requesting approval for Q4 marketing budget allocation",
        "risk_level": "medium",
        "justification": "Standard budget request following company policy"
    }
    
    # Submit for approval
    action_id = approval_system.submit_for_approval(
        sample_action, 
        ApprovalType.FINANCIAL
    )
    
    print(f"Sample action submitted: {action_id}")
    
    # Show pending approvals
    pending = approval_system.get_pending_approvals()
    print(f"Currently pending approvals: {len(pending)}")
    
    print("Human Approval System initialized!")
    print("- Approval submission functionality ready")
    print("- Notification system operational")
    print("- Approval tracking implemented")

if __name__ == "__main__":
    main()